package tg.geeknation.rajkat.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PROFIL".
 */
public class Profil implements java.io.Serializable {

    private Long id;
    private String nom;
    private String competence;
    private Integer photo;

    public Profil() {
    }

    public Profil(Long id) {
        this.id = id;
    }

    public Profil(Long id, String nom, String competence, Integer photo) {
        this.id = id;
        this.nom = nom;
        this.competence = competence;
        this.photo = photo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getCompetence() {
        return competence;
    }

    public void setCompetence(String competence) {
        this.competence = competence;
    }

    public Integer getPhoto() {
        return photo;
    }

    public void setPhoto(Integer photo) {
        this.photo = photo;
    }

}
