package tg.geeknation.rajkat.models.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import tg.geeknation.rajkat.models.Profil;

import tg.geeknation.rajkat.models.dao.ProfilDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig profilDaoConfig;

    private final ProfilDao profilDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        profilDaoConfig = daoConfigMap.get(ProfilDao.class).clone();
        profilDaoConfig.initIdentityScope(type);

        profilDao = new ProfilDao(profilDaoConfig, this);

        registerDao(Profil.class, profilDao);
    }
    
    public void clear() {
        profilDaoConfig.getIdentityScope().clear();
    }

    public ProfilDao getProfilDao() {
        return profilDao;
    }

}
